server:
  port: 8091

spring:
  application:
    name: GYM-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    server-url:
      defaultZone: http://localhost:8761/eureka/
  instances:
    hostname: localhost